# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!
# source 'https://github.com/jedisct1/swift-sodium.git'
target 'Test' do
	pod 'Sodium',:git => 'https://github.com/jedisct1/swift-sodium.git'
end

target 'TestTests' do

end

target 'TestUITests' do

end
